void Reset_Accelerations( planet BD[] );
void Position_Half_Step( planet BD[] );
void Velocity_Full_Step( planet BD[] );
void leapfrog( planet BD[], int method );
void Position_Step_1( planet BD[] );
void Velocity_Step_1( planet BD[] );
void Position_Step_2( planet BD[] );
void Velocity_Step_2( planet BD[] );
void Position_Step_3( planet BD[] );
void Velocity_Step_3( planet BD[] );
void Position_Step_4( planet BD[] );
void Velocity_Step_Final( planet BD[] );
void Position_Step_Final( planet BD[] );
void omelyan( planet BD[], int method );
